### ISSUE TITLE
Missing button to install and connect..

### ISSUE THREAD

**Issue by Puribauer** [alextselegidis/easyappointments-wordpress#35]
Im not sure whats wrong.. 
most up to date WP installation and php 7.4 +MariaDB 10
Thank you in advance
Max

**Comment by alextselegidis** [comment]
Hello! 

FYI I transferred your ticket to the integrations repository. 

It looks like there's a JS issue with your installation that we will need to figure out. 

Pressing F12 on your browser it will open the developer tools that have a `console` tab that displays all error messages. 

Reload the page and send any errors you have there in here for further troubleshooting. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Hello! 

After the latest updates, this should no longer be a problem. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
